version: "3"
services:
  test_app:
    container_name: ${CONTAINER_NAME:-cn_test_app}
    build:
      context: ./../../
      dockerfile: ./docker/app/Dockerfile
    image: test_app:${SRC_VERSION}
    # volumes:
    #   - ${WEB_ROOT_STATIC:-/var/www/html/static}:/opt/app/staticfiles
    #   - ${WEB_ROOT_MEDIA:-/var/www/html/media}:/opt/app/media
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG:-True}
    ports:
      - ${APP_PORT:-8000}:8000
    entrypoint: ["gunicorn", "config.asgi", "-b", "0.0.0.0", "-w", "4", "-k", "uvicorn.workers.UvicornWorker"]
