version: "3"
services:
  test_manage:
    container_name: cn_test_manage
    build:
      context: ./../../
      dockerfile: ./docker/manage/Dockerfile
    image: test_manage:tmp
    volumes:
      - ./../..:/opt/app
      - ${WEB_ROOT_STATIC:-/var/www/html/staitc}:/opt/app/staticfiles
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate"
